# Generated by Django 5.2.8 on 2025-11-27 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('usertype', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlotTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phonenumber', models.BigIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=30, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RenalGuideApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='CaretakerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phonenumber', models.BigIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RenalGuideApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='MessageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=30, null=True)),
                ('CARETAKERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RenalGuideApp.caretakertable')),
                ('DOCTORID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RenalGuideApp.doctortable')),
            ],
        ),
        migrations.CreateModel(
            name='NurseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phonenumber', models.BigIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=30, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RenalGuideApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=30, null=True)),
                ('CARETAKERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RenalGuideApp.caretakertable')),
            ],
        ),
        migrations.CreateModel(
            name='DietTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(blank=True, max_length=30, null=True)),
                ('PATIENTID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RenalGuideApp.patienttable')),
            ],
        ),
        migrations.CreateModel(
            name='CountTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('PATIENTID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RenalGuideApp.patienttable')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('bookingdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('DOCTORID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RenalGuideApp.doctortable')),
                ('PATIENTID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RenalGuideApp.patienttable')),
            ],
        ),
        migrations.CreateModel(
            name='PostHDTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('numberofHD', models.IntegerField(blank=True, null=True)),
                ('bloodpressure', models.CharField(blank=True, null=True)),
                ('temperature', models.CharField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('weightloss', models.FloatField(blank=True, null=True)),
                ('nextappointment', models.DateField(blank=True, null=True)),
                ('PATIENTID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RenalGuideApp.patienttable')),
            ],
        ),
        migrations.CreateModel(
            name='PreHDTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('numberofHD', models.IntegerField(blank=True, null=True)),
                ('bloodpressure', models.CharField(blank=True, null=True)),
                ('temperature', models.CharField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('weightgain', models.FloatField(blank=True, null=True)),
                ('PATIENTID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RenalGuideApp.patienttable')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('APPOINTMENTID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RenalGuideApp.appointmenttable')),
                ('DOCID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RenalGuideApp.doctortable')),
            ],
        ),
        migrations.CreateModel(
            name='SlotBookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('CaretakerTable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RenalGuideApp.caretakertable')),
                ('SLOT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RenalGuideApp.slottable')),
            ],
        ),
        migrations.CreateModel(
            name='SlotnotificationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotnotification', models.CharField(blank=True, max_length=30, null=True)),
                ('SLOTBOOKINGID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RenalGuideApp.slotbookingtable')),
            ],
        ),
    ]
