# Generated by Django 5.2.8 on 2025-11-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RenalGuideApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretakertable',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
