# Generated by Django 5.2.8 on 2025-12-13 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RenalGuideApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slotbookingtable',
            old_name='CaretakerTable',
            new_name='CARETAKERID',
        ),
    ]
