# Generated by Django 5.2.8 on 2025-12-13 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RenalGuideApp', '0002_rename_caretakertable_slotbookingtable_caretakerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecordsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.ImageField(upload_to='patient_records/')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('PATIENTID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RenalGuideApp.caretakertable')),
            ],
        ),
    ]
