# Generated by Django 5.2.8 on 2025-11-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RenalGuideApp', '0002_caretakertable_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slotbookingtable',
            old_name='CaretakerTable',
            new_name='CARETAKERID',
        ),
    ]
