# Generated by Django 5.2.8 on 2025-12-16 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RenalGuideApp', '0003_patientrecordstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailabilityTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('slotduration', models.PositiveIntegerField(default=30)),
                ('DOCTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RenalGuideApp.doctortable')),
            ],
        ),
    ]
