# Generated by Django 5.2.8 on 2025-11-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RenalGuideApp', '0003_rename_caretakertable_slotbookingtable_caretakerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slotbookingtable',
            old_name='CARETAKERID',
            new_name='CaretakerTable',
        ),
    ]
