# Generated by Django 5.2.8 on 2025-11-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RenalGuideApp', '0004_rename_caretakerid_slotbookingtable_caretakertable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slotbookingtable',
            old_name='CaretakerTable',
            new_name='CARETAKERID',
        ),
    ]
