# Generated by Django 5.2.8 on 2025-12-16 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RenalGuideApp', '0004_doctoravailabilitytable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorLeaveTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_from', models.DateField()),
                ('leave_to', models.DateField()),
                ('reason', models.CharField(max_length=200)),
                ('DOCTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RenalGuideApp.doctortable')),
            ],
        ),
    ]
