# Generated by Django 5.2.8 on 2025-12-19 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RenalGuideApp', '0005_doctorleavetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoravailabilitytable',
            old_name='DOCTOR',
            new_name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctoravailabilitytable',
            name='day',
        ),
        migrations.RemoveField(
            model_name='doctoravailabilitytable',
            name='slotduration',
        ),
        migrations.AddField(
            model_name='doctoravailabilitytable',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctoravailabilitytable',
            name='status',
            field=models.CharField(default='Available', max_length=20),
        ),
    ]
