# Generated by Django 5.2.8 on 2025-12-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RenalGuideApp', '0006_rename_doctor_doctoravailabilitytable_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorleavetable',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
