# Generated by Django 5.2.8 on 2025-11-28 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RenalGuideApp', '0006_rename_caretakerid_slotbookingtable_caretakertable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posthdtable',
            name='nextappointment',
        ),
    ]
