# Generated by Django 5.2.8 on 2025-11-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RenalGuideApp', '0007_remove_posthdtable_nextappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='posthdtable',
            name='nextappointment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
