# Generated by Django 5.2.8 on 2025-12-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RenalGuideApp', '0007_alter_doctorleavetable_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorleavetable',
            name='leave_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='doctorleavetable',
            name='leave_to',
            field=models.DateTimeField(),
        ),
    ]
