# Generated by Django 5.2.8 on 2025-12-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RenalGuideApp', '0008_posthdtable_nextappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortable',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patienttable',
            name='bloodgroup',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patienttable',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
