# Generated by Django 5.2.8 on 2025-12-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RenalGuideApp', '0008_alter_doctorleavetable_leave_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorleavetable',
            name='leave_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctorleavetable',
            name='leave_to',
            field=models.DateField(),
        ),
    ]
