# Generated by Django 5.2.8 on 2025-12-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RenalGuideApp', '0009_alter_doctorleavetable_leave_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorleavetable',
            name='Status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
