# Generated by Django 5.2.8 on 2025-12-20 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RenalGuideApp', '0010_doctorleavetable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecordstable',
            name='DOCTORID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RenalGuideApp.doctortable'),
        ),
        migrations.AddField(
            model_name='patientrecordstable',
            name='Dateofconsultation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecordstable',
            name='Description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
