# Generated by Django 5.2.8 on 2025-12-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RenalGuideApp', '0011_patientrecordstable_doctorid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecordstable',
            name='DOCTORID',
        ),
        migrations.AddField(
            model_name='patientrecordstable',
            name='DoctorName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecordstable',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
