# Generated by Django 5.2.8 on 2025-12-27 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RenalGuideApp', '0012_remove_patientrecordstable_doctorid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posthdtable',
            name='nextappointment',
        ),
        migrations.RemoveField(
            model_name='posthdtable',
            name='temperature',
        ),
    ]
