# Generated by Django 5.2.8 on 2025-12-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RenalGuideApp', '0013_remove_posthdtable_nextappointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptiontable',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
